<a href="https://colab.research.google.com/github/NamalSanjaya/CV_A04/blob/main/Original_Assignment04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data() ## Loading the data set

170500096/170498071 [==============================] - 2s 0us/step


In [ ]:
x_train_copy , x_test_copy = x_train.copy() , x_test.copy()

In [ ]:
K = len(np.unique(y_train)) # Classes
Ntr = x_train.shape[0]

Nte = x_test.shape[0]
Din = 3072 # CIFAR10
# Din = 784 # MINIST

# Normalize pixel values

x_train, x_test = x_train / 255.0, x_test / 255.0
mean_image = np.mean(x_train, axis=0)
x_train = x_train - mean_image
x_test = x_test - mean_image

y_train = tf.keras.utils.to_categorical(y_train, num_classes=K)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=K)
x_train = np.reshape(x_train,(Ntr,Din))
x_test = np.reshape(x_test,(Nte,Din))
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')



In [ ]:
Ntr,Nte

(50000, 10000)

In [ ]:
def Square_Error(predict,true):
  return (1/Ntr) * np.sum( (true - predict)**2)

def sigmoid(arr):
  return 1/(1+np.exp(-arr))


In [ ]:
def forward(x,y,w,b,N):
  contain = []
  for each in x:
    predict = sigmoid( np.matmul(w.T , each) + b )
    contain.append(predict)

  bag_predict = np.asarray(contain)
  loss  = Square_Error(bag_predict,y)

  return loss,bag_predict
  

In [ ]:
def W_derivatef(x,y,yht,N):
  return (2/N)*np.sum( np.matmul( x.T , (yht - y) ) )

def B_derivatef(y,yht,N):
  return (2/N)*np.sum(yht - y)

In [ ]:
def Gradient_Descent(X,Y,epochs):
  std=1e-5
  weight = std*np.random.randn(Din, K)
  baise = np.zeros(K)
  rate = 0.1

  for loops in range(epochs):
    Loss , y_hat  = forward(X,Y,weight,baise,Ntr)
    diff_W       =  W_derivatef(X,Y,y_hat,Ntr)
    diff_b       = B_derivatef(Y,y_hat,Ntr)

    weight = weight - rate * diff_W
    baise  = baise  - rate * diff_b

    print(loops+1, ") Loss : " , Loss)

  return weight,baise


In [ ]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
q = [ np.array([2,3,4]) , np.array([7,8,9] ) ] 
#print(q)
q = np.asarray(q)
print(q)

[[2 3 4]
 [7 8 9]]


In [ ]:
W , b = Gradient_Descent(x_train,y_train,10)

1 ) Loss :  2.50000651992914
2 ) Loss :  3.1274041618051953


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in exp
  """


3 ) Loss :  5.192317701713423
4 ) Loss :  4.806973529342826
5 ) Loss :  5.192315892508458
6 ) Loss :  4.806671478232846
7 ) Loss :  5.192305734377718
8 ) Loss :  4.80638144519412
9 ) Loss :  5.192264003384915
10 ) Loss :  4.806100655473467


In [ ]:
x_train_copy[1][1,1]

array([145, 153, 154], dtype=uint8)

In [ ]:
W[1].shape

(10,)